### ISSUE TITLE
Error when Generating

### ISSUE THREAD

**Issue by Sikksens** [TasosY2K/protonvpn-acc-gen#2]
Hey there,

When generating a new account I get this error.

```
   ╔═══════════════════════════════╗
   ║                               ║
   ║   ProtonVPN Generator 1.0.2   ║
   ║                               ║
   ╚═══════════════════════════════╝

Coded by leandev
More info: http://l34nd3v.com
This is an unofficial tool and is not affiliated with Proton Technologies AG

? Generate a new ProtonVPN account? Yes
i Generating your account...
(node:7928) UnhandledPromiseRejectionWarning: Error: No node found for selector: #username
    at assert (C:\Users\user1\AppData\Roaming\npm-cache\_npx\7928\node_modules\protonvpn-acc-gen\node_modules\puppeteer\lib\helper.js:283:11)
    at DOMWorld.type (C:\Users\user1\AppData\Roaming\npm-cache\_npx\7928\node_modules\protonvpn-acc-gen\node_modules\puppeteer\lib\DOMWorld.js:421:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async createAccount (C:\Users\user1\AppData\Roaming\npm-cache\_npx\7928\node_modules\protonvpn-acc-gen\bin\app.js:65:3)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\user1\AppData\Roaming\npm-cache\_npx\7928\node_modules\protonvpn-acc-gen\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.type (C:\Users\user1\AppData\Roaming\npm-cache\_npx\7928\node_modules\protonvpn-acc-gen\node_modules\puppeteer\lib\Page.js:1103:29)
    at createAccount (C:\Users\user1\AppData\Roaming\npm-cache\_npx\7928\node_modules\protonvpn-acc-gen\bin\app.js:65:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7928) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by 0x3dward** [comment]
**ok and?**

**Comment by Sikksens** [comment]
ok and what?

**Comment by pasenidis** [comment]
what ok and what?

**Comment by 0x3dward** [comment]
I am an open source contributor, just trying to understand what's wrong here.

**Comment by 0x3dward** [comment]
Hey, sorry for the previous inconvenience. As it turns out, the registration form has changed a bit and that's why Puppeteer is throwing an error. I will update Lean concerning this.

**Comment by VisualEhrmanntraut** [comment]
You're bad at GitHub @pasenidis

**Comment by 0x3dward** [comment]
h

**Comment by onetastydrumstick** [comment]
how tf is this error still a thing

**Comment by VisualEhrmanntraut** [comment]
He isn't working on it

**Comment by onetastydrumstick** [comment]
we live in a society
